export const chatDetails = [
  {
    id: 1,
    title: "Alice",
    imageURL: "https://picsum.photos/id/237/200/300",
    orderId: "OD1234567890",
    latestMessageTimestamp: "21/06/2023",
    messageList: [
      {
        messageId: "msg1",
        message: "Hey Alice, How are you?",
        timestamp: "21/06/2023",
        sender: "BOT",
        messageType: "text",
      },
      {
        messageId: "msg2",
        message: " I'm good. How are you?",
        timestamp: "21/06/2023",
        sender: "USER",
        messageType: "text",
      },
      {
        messageId: "msg3",
        message: "I'm fine, Thanks!",
        timestamp: "21/06/2023",
        sender: "BOT",
        messageType: "text",
      },
      {
        messageId: "msg4",
        message: "And how was your weekend?",
        timestamp: "21/06/2023",
        sender: "BOT",
        messageType: "text",
      },
      {
        messageId: "msg5",
        message: "It was great!.",
        timestamp: "21/06/2023",
        sender: "USER",
        messageType: "text",
      },
      {
        messageId: "msg6",
        message: "That sounds fun! Where did you go?",
        timestamp: "21/06/2023",
        sender: "BOT",
        messageType: "text",
      },
      {
        messageId: "msg7",
        message: "In my hometown",
        timestamp: "21/06/2023",
        sender: "USER",
        messageType: "text",
      },
      {
        messageId: "msg8",
        message: "Nice!",
        timestamp: "21/06/2023",
        sender: "BOT",
        messageType: "text",
      },
      {
        messageId: "msg9",
        message: "What's was your plan",
        timestamp: "21/06/2023",
        sender: "USER",
        messageType: "text",
      },
    ],
  },
  {
    id: 2,
    title: "Bob",
    imageURL: "https://picsum.photos/id/238/200/300",
    orderId: "OD1234567891",
    latestMessageTimestamp: "20/09/2021",
    messageList: [
      {
        messageId: "msg1",
        message: "Hey Bob, did you catch the game last night?",
        timestamp: "20/09/2021",
        sender: "BOT",
        messageType: "text",
      },
      {
        messageId: "msg2",
        message: "Yes, it was intense! Can't believe that last-minute goal.",
        timestamp: "20/09/2021",
        sender: "USER",
        messageType: "text",
      },
      {
        messageId: "msg3",
        message: "I know right! It was a nail-biter.",
        timestamp: "20/09/2021",
        sender: "BOT",
        messageType: "text",
      },
    ],
  },
  {
    id: 3,
    title: "Clara",
    imageURL: "https://picsum.photos/id/239/200/300",
    orderId: "OD1234567892",
    latestMessageTimestamp: "08/09/2021",
    messageList: [
      {
        messageId: "msg3",
        message: "Hi Clara, how's your new project going?",
        timestamp: "08/09/2021",
        sender: "BOT",
        messageType: "text",
      },
      {
        messageId: "msg4",
        message: "It's going well, but it's a lot of work.",
        timestamp: "08/09/2021",
        sender: "USER",
        messageType: "text",
      },
      {
        messageId: "msg5",
        message: "I bet! Let me know if you need any help.",
        timestamp: "08/09/2021",
        sender: "BOT",
        messageType: "text",
      },
    ],
  },
  {
    id: 4,
    title: "Max",
    imageURL: "https://picsum.photos/id/139/200/300",
    orderId: "OD1234567893",
    latestMessageTimestamp: "26/08/2021",
    messageList: [
      {
        messageId: "msg5",
        message: "Hey Max, what are your weekend plans?",
        timestamp: "24/08/2021",
        sender: "BOT",
        messageType: "text",
      },
      {
        messageId: "msg6",
        message: "Not much, just going to relax and watch some movies.",
        timestamp: "24/08/2021",
        sender: "USER",
        messageType: "text",
      },
      {
        messageId: "msg7",
        message: "Sounds like a perfect plan!",
        timestamp: "25/08/2021",
        sender: "BOT",
        messageType: "text",
      },
    ],
  },
  {
    id: 5,
    title: "Irris",
    imageURL: "https://picsum.photos/id/89/200/300",
    orderId: "OD1234567894",
    latestMessageTimestamp: "03/05/2021",
    messageList: [
      {
        messageId: "msg1",
        message: "Hi Irris, how's the weather over there?",
        timestamp: "03/05/2021",
        sender: "BOT",
        messageType: "text",
      },
      {
        messageId: "msg2",
        message: "It's pretty sunny, thinking of going for a walk.",
        timestamp: "03/05/2021",
        sender: "USER",
        messageType: "text",
      },
      {
        messageId: "msg3",
        message: "That sounds like a good idea! Enjoy the sunshine.",
        timestamp: "03/05/2021",
        sender: "BOT",
        messageType: "text",
      },
    ],
  },
  {
    id: 6,
    title: "Elli",
    imageURL: "https://picsum.photos/id/79/200/300",
    orderId: "OD1234567895",
    latestMessageTimestamp: "27/08/2020",
    messageList: [
      {
        messageId: "msg1",
        message: "Hey Elli, what book are you reading right now?",
        timestamp: "27/08/2020",
        sender: "BOT",
        messageType: "text",
      },
      {
        messageId: "msg2",
        message: "I'm reading a mystery novel. It's really gripping!",
        timestamp: "27/08/2020",
        sender: "USER",
        messageType: "text",
      },
      {
        messageId: "msg3",
        message: "Nice! I love a good mystery.",
        timestamp: "27/08/2020",
        sender: "BOT",
        messageType: "text",
      },
    ],
  },
  {
    id: 7,
    title: "Rubby",
    imageURL: "https://picsum.photos/id/69/200/300",
    orderId: "OD1234567896",
    latestMessageTimestamp: "27/08/2020",
    messageList: [
      {
        messageId: "msg1",
        message: "Hi Rubby, how are you doing today?",
        timestamp: "27/08/2020",
        sender: "BOT",
        messageType: "text",
      },
      {
        messageId: "msg2",
        message: "I'm doing well, just a bit busy with work.",
        timestamp: "27/08/2020",
        sender: "USER",
        messageType: "text",
      },
      {
        messageId: "msg3",
        message: "Hang in there! Don't forget to take breaks.",
        timestamp: "27/08/2020",
        sender: "BOT",
        messageType: "text",
      },
    ],
  },
  {
    id: 9,
    title: "Zoe",
    imageURL: "https://picsum.photos/id/11/50/300",
    orderId: "OD1234567896",
    latestMessageTimestamp: "27/08/2020",
    messageList: [
      {
        messageId: "msg1",
        message: "Hey Zoe, any plans for the evening?",
        timestamp: "27/08/2020",
        sender: "BOT",
        messageType: "text",
      },
      {
        messageId: "msg2",
        message: "I'm thinking of trying out a new recipe.",
        timestamp: "27/08/2020",
        sender: "USER",
        messageType: "text",
      },
      {
        messageId: "msg3",
        message: "That sounds delicious! What are you making?",
        timestamp: "27/08/2020",
        sender: "BOT",
        messageType: "text",
      },
    ],
  },
  {
    id: 10,
    title: "Sam",
    imageURL: "https://picsum.photos/id/53/50/300",
    orderId: "OD1234567896",
    latestMessageTimestamp: "27/08/2020",
    messageList: [
      {
        messageId: "msg1",
        message: "Hi Sam, how's your new job going?",
        timestamp: "27/08/2020",
        sender: "BOT",
        messageType: "text",
      },
      {
        messageId: "msg2",
        message: "It's going well! Still getting the hang of things.",
        timestamp: "27/08/2020",
        sender: "USER",
        messageType: "text",
      },
      {
        messageId: "msg3",
        message: "Glad to hear that! You'll be a pro in no time.",
        timestamp: "27/08/2020",
        sender: "BOT",
        messageType: "text",
      },
    ],
  },
  {
    id: 11,
    title: "Veer",
    imageURL: "https://picsum.photos/id/57/50/300",
    orderId: "OD1234567896",
    latestMessageTimestamp: "27/08/2020",
    messageList: [],
  },
  {
    id: 12,
    title: "Riya",
    imageURL: "https://picsum.photos/id/44/50/300",
    orderId: "OD1234567896",
    latestMessageTimestamp: "27/08/2020",
    messageList: [],
  },
];
